server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.178.144:3306/testgroup?serverTimezone=GMT%2B8
    username: testgroup
    password: Sgcc_1234


#开启日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

flag:
  readOnly: true

